import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import ToysPhotography from "../components/ToysPhotography";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blackjo Diorama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blackjo-icon.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />
      <Hero />
      <Projects />
      <ToysPhotography />
    </div>
  );
}
