import Head from "next/head";
import Image from "next/image";
import AboutMe from "../components/AboutMe";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Order from "../components/Order";
import Projects from "../components/Projects";
import styles from "../styles/Home.module.css";

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Blackjo Diorama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blackjo-icon.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"/>
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;700&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="css/animate.css"/>

      </Head>

      <Navbar />
      <Hero />
      <Projects />
      <AboutMe />
      <Order />
      <Contact />
      <Footer />
    </div>
  );
}
